import { Roboto_Mono } from "next/font/google";
import "./globals.css";

const roboto_mono = Roboto_Mono({
  weight: '300',
  subsets: ["latin"]
});

export const metadata = {
  title: "Memory Game",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={roboto_mono.className}>{children}</body>
    </html>
  );
}
